package edu.yu.com3640.Impl;

import java.util.ArrayList;
import java.util.List;

import edu.yu.com3640.Pixel;

/**
 * This class is responsible for mapping a given color to the closest color in a
 * fixed palette of 256 colors.
 */
public class ColorMapperSampleCode {

    private final List<Pixel> palette;

    public ColorMapperSampleCode() {
        this.palette = generateFixedPalette();
    }

    public List<Pixel> getPalette() {
        return palette;
    }

    public int findClosestColorIndex(Pixel pixel) {
        int minDistance = Integer.MAX_VALUE;
        int closestIndex = 0;
        for (int i = 0; i < palette.size(); i++) {
            Pixel p = palette.get(i);
            int distance = colorDistance(pixel, p);
            if (distance < minDistance) {
                minDistance = distance;
                closestIndex = i;
            }
        }
        return closestIndex;
    }

    /**
     * Calculates the distance between two colors. The distance is calculated as
     * the sum of the squares of the differences between the red, green, and blue
     * components of the two colors.
     * 
     * @param p1
     * @param p2
     * @return
     */
    private int colorDistance(Pixel p1, Pixel p2) {
        int redDiff = p1.getRed() - p2.getRed();
        int greenDiff = p1.getGreen() - p2.getGreen();
        int blueDiff = p1.getBlue() - p2.getBlue();
        return redDiff * redDiff + greenDiff * greenDiff + blueDiff * blueDiff;
    }

    /**
     * Generates a fixed palette of up to 256 colors. The colors are generated by
     * incrementing the red, green, and blue components by 51. The red component
     * starts at 0 and ends at 255. The green component starts at 0 and ends at 255.
     * The blue component starts at 0 and ends at 255.
     * 
     * @return
     */
    private List<Pixel> generateFixedPalette() {
        // Generate a simple fixed palette with 256 colors
        List<Pixel> palette = new ArrayList<>();
        for (int r = 0; r < 256; r += 51) {
            for (int g = 0; g < 256; g += 51) {
                for (int b = 0; b < 256; b += 51) {
                    palette.add(new Pixel(r, g, b));
                }
            }
        }
        return palette;
    }
}
